//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    using RegressionEntities;
    
    public partial class RegressionToolEntities : DbContext
    {
        public RegressionToolEntities()
            : base("name=RegressionToolEntities")
        {
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<Regression> Regressions { get; set; }
        public virtual DbSet<Regression_ASP_TP> Regression_ASP_TP { get; set; }
        public virtual DbSet<RegressionFile> RegressionFiles { get; set; }
        public virtual DbSet<RegressionStatu> RegressionStatus { get; set; }
    }
}
