//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionEntities
{
    using System;
    using System.Collections.Generic;
    
    
    using System.Runtime.Serialization;
    
    [Serializable]
    public partial class Regression
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regression()
        {
    		this.Regression_ASP_TP = new HashSet<Regression_ASP_TP>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public string MapName { get; set; }
        [DataMember]
        public Nullable<int> StatusId { get; set; }
        [DataMember]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [DataMember]
        public virtual LoginUser LoginUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Regression_ASP_TP> Regression_ASP_TP { get; set; }
        [DataMember]
        public virtual RegressionStatu RegressionStatu { get; set; }
    }
}
