//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionEntities
{
    using System;
    using System.Collections.Generic;
    
    
    using System.Runtime.Serialization;
    
    [Serializable]
    public partial class RegressionFile
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int Regression_ASP_TPID { get; set; }
        [DataMember]
        public string PresTranslatedFilename { get; set; }
        [DataMember]
        public string PostTranslatedFilename_ { get; set; }
        [DataMember]
        public string LocalLoationPreTranslatedFile { get; set; }
        [DataMember]
        public string LocalLoationPostTranslatedFile { get; set; }
        [DataMember]
        public System.DateTime TransDate { get; set; }
        [DataMember]
        public Nullable<bool> Matching { get; set; }
        [DataMember]
        public int StatusId { get; set; }
    
        [DataMember]
        public virtual Regression_ASP_TP Regression_ASP_TP { get; set; }
        [DataMember]
        public virtual RegressionStatu RegressionStatu { get; set; }
    }
}
