//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionEntities
{
    using System;
    using System.Collections.Generic;
    
    
    using System.Runtime.Serialization;
    
    [Serializable]
    public partial class RegressionStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegressionStatu()
        {
    		this.Regressions = new HashSet<Regression>();
    		this.Regression_ASP_TP = new HashSet<Regression_ASP_TP>();
    		this.RegressionFiles = new HashSet<RegressionFile>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int StatusType { get; set; }
        [DataMember]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Regression> Regressions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Regression_ASP_TP> Regression_ASP_TP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<RegressionFile> RegressionFiles { get; set; }
    }
}
