//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionEntities
{
    using System;
    using System.Collections.Generic;
    
    
    using System.Runtime.Serialization;
    
    [Serializable]
    public partial class Regression_ASP_TP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regression_ASP_TP()
        {
    		this.RegressionFiles = new HashSet<RegressionFile>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int RegressionId { get; set; }
        [DataMember]
        public int Asp_tpId { get; set; }
        [DataMember]
        public string Asp_tpCode { get; set; }
        [DataMember]
        public string Client { get; set; }
        [DataMember]
        public string Utility { get; set; }
        [DataMember]
        public Nullable<int> Matches { get; set; }
        [DataMember]
        public Nullable<int> Diff { get; set; }
        [DataMember]
        public int StatusId { get; set; }
    
        [DataMember]
        public virtual Regression Regression { get; set; }
        [DataMember]
        public virtual RegressionStatu RegressionStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<RegressionFile> RegressionFiles { get; set; }
    }
}
